sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
matrix:
  allow_failures:
    - node_js: "5"
  # # Add a build with screenshot uploads for Node.js@6
  # include:
  #   - node_js: "6"
  #     env: UPLOAD_RESULTS="TRUE"

# Set up g++ dependencies for png-img
# https://github.com/gemini-testing/gemini/blob/v4.13.4/.travis.yml#L12
# https://github.com/gemini-testing/gemini/blob/v4.13.4/.travis.yml#L59-L65
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
  # Install Firefox for Karma tests
  # https://docs.travis-ci.com/user/firefox/#Version-aliases
  firefox: latest

before_install:
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

script:
  # Run tests (upon failure, upload to Imgur)
  - 'npm test || ((test "$UPLOAD_RESULTS" = "TRUE" && bin/test-browser-upload-screenshots.sh) && exit 1)'

  # Verify demo generates and there are no changes
  - npm run generate-demo
  - git diff --exit-code

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
